---
title: '2019-04-17'
author: "林茂廷"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(lubridate)
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```
#[[.]]用來取出所要的「一個」元素
```{r}
plasticContainer

plasticContainer[[1]]
plasticContainer[["redBox"]]
plasticContainer[[3]][2]
```
#只取green box裡的paper
```{r}
#1
x <- plasticContainer[["greenBox"]] 
x[[1]]
#2
plasticContainer[["greenBox"]][[1]]
```


```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```

```{r}
成績單[["個經"]]
成績單[[1]]
```

```{r}
studentRecord <-
  list(
    學號="410073058",
    姓名="王小明",
    性別="男",
    學年平均成績=list(
      一年級=88,
      二年級=90.3,
      三年級=92,
      四年級=95
    )
  )

studentRecord

studentRecord[[2]]
studentRecord[[4]][[3]]
```

#[.]取一群元素 , 同時取兩個元素
```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(3,2)]
```

#[.]會保有母層 , [[.]]取出元素不會有母層
```{r}
extract1 <- plasticContainer[c("greenBox")]
extract2 <- plasticContainer[[c("greenBox")]]
extract1
extract2
```
#***只取一個用[[.]]***
```{r}
extract1[[1]][[1]]
extract2[[1]]
```

