---
title: '2019-04-24'
author: "林茂廷"
date: "4/24/2019"
output: html_document
---
```{r}
Mat1 <- matrix(
  c(1:6), 2,3
)
Mat1
class(Mat1)
typeof(Mat1)
```

```{r}
Mat2 <- matrix(
  c("a","b","c","d"), 2, 2
)
Mat2
```

```{r}
MAT2 <- matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
StuDF[[2]][[3]]
```
#data.frame()遇到變數輸入為character class時，內定會被轉成factor
```{r}
class(StuDF$姓名)
```

```{r}
StuDF$姓名 <- as.character(StuDF$姓名)
class(StuDF$姓名)
```
#取消內定character為factor的方式
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```

```{r}
class(StuDF2$姓名)
```

```{r}
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
```

```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```

#[.R , .C] object extraction ; .R:代表哪幾列 / .C:代表哪幾行
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:15]
m <- matrix(chosenLETTERS,5,3)
m
```

```{r}
chosenLETTERS[[9]]
m[[9]]
m[3,3]
m[c(1,3),c(2,2)]
```
#若只用[.] extraction, 如何取出matObj1[c(1,5),c(2,3)]的元素值？
```{r}
m[c(T,F,F,T,F),c(F,T,T)]
m[c(1,4),c(F,T,T)]
```

