---
title: "Untitled"
author: "Alicia"
date: "2019年5月15日"
output: html_document
---

```{r}
Vector1 <- letters[1:6]
Vector1
names(Vector1)
```

```{r}
names(Vector1) <- c('名稱1','名稱2','名稱3','名稱4','名稱5','名稱6')
names(Vector1)
```

```{r}
Vector1[["名稱4"]]
```

##colnames / rownames

#colnames
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2
```

```{r}
colnames(StuDF2)
names(StuDF2)
```
全部名稱改
```{r}
colnames(StuDF2) <- c("col1","col2","col3")
colnames(StuDF2)
StuDF2
```
只改col2的名稱
```{r}
colnames(StuDF2)[[2]] <- c("姓名")
colnames(StuDF2)
StuDF2
```
改col2,3的名稱
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grade")
colnames(StuDF2)
StuDF2
```

```{r}
colnames(StuDF2) <- c("studentID","name","grade")
colnames(StuDF2)
StuDF2
```
#rownames()
```{r}
rownames(StuDF2)
rownames(StuDF2) <- str_c("第",1:5,"筆")
rownames(StuDF2)
StuDF2
```

##新增 / 取代
```{r}
a <- c("1","b","TRUE")
a
a[[2]] <- "c" #元素存在
a[[5]] <- "7" #元素不存在
a
```
請將下面的TRUE換成FALSE, 並增加第5個元素其值為數字7。
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]] <- FALSE  # b$元素3 <- FALSE  # b[["元素3"]] <- FALSE
b$新元素 <- "7"  # b[["新元素"]] <- "7"
                  # b[c(3,5)] <- c(FALSE,"7")
b
```
使用"元素名稱"創新元素
```{r}
names(b)
b[["新元素A"]] <- c(1,2,3)
b$新元素B <- c(T,F,T)
b
```

```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```

取出「期間」變數轉成date class
```{r}
exData3$期間 <- ymd(exData3$期間)
exData3
```

增加一個「isAsiaCrisis」的logical變數，其值為TRUE若「期間」介於1997-06-01到1998-12-01（含前後）
```{r}
isAsiaCrisis <- exData3$期間 <= ymd("1998-12-01") & exData3$期間 >= ymd("1997-06-01")
isAsiaCrisis
```

利用「isAsiaCrisis」值，結合使用[.R,.C]取出1997-06-01到1998-12-01亞洲金融危機的子樣本
```{r}
logiAsiaCrisis <- exData3$isAsiaCrisis
exData3[logiAsiaCrisis, ]
#合在一起
exData3[exData3$isAsiaCrisis==T, ]
```

#8.1.1
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
class(utility_cobb_douglass)
```
f(x,a) = a+x
```{r}
F_n <- function(x,.alpha){
  F <- x + .alpha
  return(F)
}
```

#8.1.2範例
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
studentID <-"92aS67fee" 
transcriptDataFinal$學號==studentID -> logiChosenStudent
sum(transcriptDataFinal$學期成績[logiChosenStudent]*
  transcriptDataFinal$學分數[logiChosenStudent])/
  sum(transcriptDataFinal$學分數[logiChosenStudent]) -> GPA
```

```{r}
log<-transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[log,]
```
