---
title: '2019-03-27'
author: "林茂廷"
date: "3/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lubridate)
```

```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
```
#轉換時區
```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
as.double(LisbonDateTime)
```

```{r}
USDateTime <- with_tz(twDateTime,tzone = "America/New_York")
typeof(USDateTime)
as.double(twDateTime)
as.double(USDateTime)
```

```{r}
dt <- mdy_hms("03-14-2019 8:18:47")
dt1 <- ymd("2018-09-11")
dt2 <- mdy("March 3 2019")
```
#與1970-01-01相差的日數
```{r}
as.integer(ymd("1970-01-01"))
as.integer(ymd("1970-01-02"))
as.integer(ymd("2019-03-11"))
```
#加減乘除
```{r}
a <- c(1, 5, -3)
b <- c(0.5, 12, 2)
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
class(a)
a+bL
a-bL
aL+bL
a*b
a%%b
c <- 4
c+a
```
#時間相減
```{r}
twDateTime <- ymd_hms("2019-03-18 14:04:00", tz="Asia/Taipei")
twDateTime1 <- ymd_hms("2019-03-20 15:04:35", tz="Asia/Taipei")
twDateTime2 <- ymd_hms("2019-02-01 15:04:30", tz="Asia/Taipei")
```

```{r}
twDateTime1 -twDateTime2
```

```{r}
startingDate <- ymd("2000-02-17")
startingDate + years(1)
startingDate + dyears(1)
ymd("2000-02-01") -> startingDate
ymd("2019-08-11") -> endingDate
endingDate - startingDate
```

```{r}
x <- 5
y <- 7
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```
#==等於!=不等於
```{r}
x < x2
x2 == y2
x2 != y2
```
# %in%屬於
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)

x4 %in% y4

x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```
#NA
```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

x2 
is.na(x2)
```

```{r}
sum(x2)
sum(x2,na.rm=F)
sum(x2,na.rm=T)
```

