---
title: '2015-05-22'
author: "林茂廷"
date: "5/22/2019"
output: html_document
---

## midterm 6.2

```{r}
library(readr)
invoiceList <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/invoiceList.csv",
col_types = cols(訂單時間.以訂單時區顯示. = col_character()))
```
期中考6.2轉UTC
```{r}
invoiceList$訂單時區 == "America/New_York" -> nyLogical
invoiceList$訂單時區 == "Asia/Taipei" -> tpLogical
invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

nyDateTime<-ymd_hms(invoiceList$訂單時間.以訂單時區顯示.[nyLogical],tz="America/New_York")

tpDateTime<-ymd_hms(invoiceList$訂單時間.以訂單時區顯示.[tpLogical],tz="Asia/Taipei")

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```

```{r}
tzchange <- function(fromz,toZ){
  invoiceList$訂單時區 == fromz -> Logical
  invoiceList$Logical <- Logical

  DateTime<-ymd_hms(invoiceList$訂單時間.以訂單時區顯示.[Logical],tz=fromz)

  invoiceList$UTC時間[Logical] <- with_tz(nyDateTime,tzone=toZ)
  return(invoiceList$UTC時間[Logical])
}
tzchange("America/New_York","Asia/Taipei")
```


*8.1.1 範例2*
```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")



gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}

gpa_fun("479W9ee8e")
gpa_fun("9efW9aea5")
```




課堂練習
*##Function轉換時區*
```{r}
ymd_hms_tzChange("1973-02-21 12:05:22","America?New _York","Asia/Taipei")
```

請把以America/New_York時區輸入的時間字串"1973-02-21 12:05:22"，轉成date time class, 再改成Asia/Taipei時間顯示。
ymd_hms_tzChange(input,fromTzone,toTzone)
```{r}
ymd_hms("1973-02-21 12:05:22",tz="America/New_York") ->fromDateTime #input
with_tz(fromDateTime,tz="Asia/Taipei") ->toDateTime
toDateTime   #output
```

```{r}
ymd_hms_tzChange <- function(input,fromTzone,toTzone){
  ymd_hms(input,tz=fromTzone) -> fromDateTime 
  with_tz(fromDateTime,tzone=toTzone) ->toDateTime
  return(toDateTime) 
}

ymd_hms_tzChange("1973-02-21 12:05:22","America/New_York","Asia/Taipei")
```




民國年月
```{r}
library(stringr)
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates
twDates
```

[:digit:]+ -> 取出數字們(0~9) 
```{r}
library(stringr); library(lubridate)
yyyy<-as.integer(str_extract(twDates,"(?<=(民國))[:digit:]+"))+1911
mm<-str_extract(twDates,"[:digit:]+(?=月)")
yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
yyyymmdd
```


若要常常轉換不同民國年月成西元date，以上述程序為例，何者為input？何者為output?

請寫一個函數其名稱為date_convert_twYM，且date_convert_twYM(x)可以把一個民國年月字串物件x轉成date time class的西元年月日物件輸出。

```{r}
sample(99:103,15,replace = T)-> yy
sample(1:12,15,replace=T)-> mm
str_c("民國",str_pad(yy,3,"left","0"),"年",mm,"月") -> twDates_New
twDates_New

# date_convert_twYM(twDates_New)
# date_convert_twYM(twDates_New,dd="04")
```


dd沒有預設值
```{r}
date_convert_twYM <- function(twdate){
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,"01",sep="-"))
  return(yyyymmdd)
}

date_convert_twYM(twDates_New)
```

dd有預設值 (dd=01 <- dd是一個numeric ; dd="01" <- dd是一個character)
```{r}
date_convert_twYM <- function(twdate,dd="01"){
  yyyy<-as.integer(str_extract(twdate,"(?<=(民國))[:digit:]+"))+1911
  mm<-str_extract(twdate,"[:digit:]+(?=月)")
  yyyymmdd <- ymd(str_c(yyyy,mm,dd,sep="-"))
  return(yyyymmdd)
}
date_convert_twYM(twDates_New)
date_convert_twYM(twDates_New,dd="04")
```


*8.1.2*

##預設
```{r}
utility_cobb_douglass2 <- function(x,y,.alpha=0.5,.beta=0.5){
  utilValue <- x^.alpha*y^.beta
  return(utilValue)
}
```

```{r}
utility_cobb_douglass2(1,2) # 使用預設值
utility_cobb_douglass2(1,2,0.5,0.8) # 自定參數值
```








