---
title: '2019-04-03'
author: "林茂廷"
date: "3/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3 == y3
x3 != y3
!(x3 == y3)
```
# ! negation


```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$幣別
```
#head 用來顯示物件前6筆值
```{r}
head(currency)
levels(currency)
class(currency)
```
#資料並沒有被當成factor class
#更正為factor class
```{r}
currency <- as.factor(currency)
#新物件 / 舊物件
class(currency)
levels(currency)
```

length():數向量內的元素個素(向量長度)
```{r}
step1_extractlevelsVector <- levels(currency)
step1_extractlevelsVector
```

```{r}
step2_countVectorlength<- length(step1_extractlevelsVector)
step2_countVectorlength
```

```{r}
length(levels(currency))
```

Q.多少筆日圓資料
```{r}
head(currency)
levels(currency)
```
#先判斷currency是否為:日圓JPY/USD
#再將值相加(總和sum)True=1 False=0
```{r}
currency == "日圓JPY/USD"
sum(currency == "日圓JPY/USD")
```

#邏輯運算
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")
y5 == "女"

!(y5 == "女")
```

```{r}
x5 %in% greatTaipei
y5 == "女"

(x5 %in% greatTaipei) & (y5 == "女")
#同時來自greatTaipei又是女性
```
which():第幾筆資料
```{r}
which((x5 %in% greatTaipei) & (y5 == "女"))
```

```{r}
(x5 %in% greatTaipei)
(y5 == "女")

(x5 %in% greatTaipei) | (y5 == "女")
which((x5 %in% greatTaipei) | (y5 == "女"))
```


```{r}
x5 %in% greatTaipei
y5 == "女"

xor(x5 %in% greatTaipei, y5 == "女")
which(xor(x5 %in% greatTaipei, y5 == "女"))
```


總和練習
```{r}
library(readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
date <- as.character(exData2$期間)
currency <- exData2$幣別
exchangeRate <- exData2$匯率
```

#請把date的class存成date class。
```{r}
#要先引入lubridate
library(lubridate)
date <- ymd(date)
class(date)
```

#1980-08-01之後的資料有多少筆。
```{r}
isAfter19800801 <-
  date >= ymd("1980-08-01")
class(isAfter19800801)
sum(isAfter19800801)
```

```{r}
head(as.integer(date))
as.integer(ymd("1980-08-01"))
head(date >= ymd("1980-08-01"))
```

幣別為“歐元USD/EUR”的資料有多少筆。
```{r}
currency == "歐元USD/EUR"
sum(currency == "歐元USD/EUR")
```
  #有將currency轉成factor class#
```{r}
currency <- as.factor(currency)
isEURO <- currency == "歐元USD/EUR"
sum(isEURO)
```

exchangeRate有多少筆NA。
```{r}
is.na(exchangeRate)
sum(is.na(exchangeRate))
```

#排除NA後，幣別為“歐元USD/EUR”的資料有多少筆。
```{r}
!(is.na(exchangeRate))
EXNA_isEURO <-
  !(is.na(exchangeRate)) & currency == "歐元USD/EUR"
sum(EXNA_isEURO)
```
老師作法:
```{r}
isNotNA <- !(is.na(exchangeRate))
isEuro <- currency == "歐元USD/EUR"
satisfyBoth <- isNotNA & isEuro
sum(satisfyBoth)
```
另一種先不存成isNotNA,isEuro的寫法
```{r}
satisfyboth <-
  !is.na(exchangeRate) & currency == "歐元USD/EUR"
sum(satisfyboth)
```










