---
title: "2019-05-29-aliciaora"
author: "Alicia"
date: "2019年5月29日"
output: html_document
---

```{r}
now2 <- function(){
  currentDateTime <- Sys.time()
  hh<-hour(currentDateTime)
  mm<-minute(currentDateTime)
  cat("現在是",hh,"點",mm,"分")
}
```

```{r}
now2()
xx <- now2()
```

browseURL()函數可以輸入網址後自動開啟瀏覽器連到該網頁
```{r}
browseURL("https://www.ntpu.edu.tw")

textbookURL <- function(){
  browseURL("https://via.hypothes.is/https://bookdown.org/tpemartin/ntpu-programming-for-data-science/")
}
textbookURL()
```




```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}
```

```{r}
gpa_fun2 <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(
    list(
      平均成績=GPA,
      成績單=subSample
      )
  )
}
```

```{r}
gpa_fun2("92aS67fee") ->outputValue
outputValue$平均成績
outputValue$成績單
```



創造一個demand_supply_fun(P,a,b,c,d)，它會輸出一個list包含三個元素：供給量，需求量，超額供給量
Qs=a+b∗P
Qd=c−d∗P
```{r}
demand_supply_fun <- function(P,a,b,c,d){
  Qs <- a + b*P
  Qd <- c - d*P
  return(
    list(
      供給量 = Qs,
      需求量 = Qd,
      超額供給量 = Qs - Qd
    )
  )
}
demand_supply_fun(1,0,1,10,2)
```


#條件執行

print()是單純的訊息輸出，而message()是用在「錯誤」狀況下的訊息顯示

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
}
```

```{r}
supply_fun2 <- function(P,a,b){
  Qs <- a+b*P
  if(P>=0) {
    return(Qs)
  }
}
supply_fun2(P=-1,0,1)
supply_fun2(P=2,0,1)
```

```{r}
a <-  readline(prompt = "請輸入一個數字： ")
if(a < 0) {
  print("a為負值")
} else {
  print("a不為負值")
}
```

```{r}
supply_fun3 <- function(P,a,b){
  Qs <- a+b*P
  if(P < 0) {
    message("P不能為負值") # 在螢幕出現的「錯誤」提示，沒有輸出任何值
  } else {
    return(Qs)
  }
}
supply_fun3(P=-1,0,1) -> yy
supply_fun3(P=2,0,1)
```






gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```{r}
gpa_fun <- function(studentID){
  if (studentID != transcriptDataFinal$學號){
  message("查無此學號") } else{
      
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  
  subSample <- transcriptDataFinal[logiChosenStudent,]
  
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  
   return(GPA) 
  }
  
}

gpa_fun("92aS67fee")
gpa_fun("aa829838s")
```


```{r}
gpa_fun <- function(studentID){
  if (studentID %in% transcriptDataFinal$學號){
  transcriptDataFinal$學號==studentID -> logiChosenStudent
  subSample <- transcriptDataFinal[logiChosenStudent,]
  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
  } else{
    message("查無此學號")
  }
}

gpa_fun("92aS67fee")
gpa_fun("aa829838s")
```
```

